/* config.js — generated by the build. Public settings only: the Supabase anon key is designed to be public. */
window.APP_CONFIG = {
  "slug": "debate-simulator",
  "name": "Debate Arena",
  "supabaseUrl": "https://izyyaxovwwvjrladiumv.supabase.co",
  "supabaseAnonKey": "sb_publishable_nCqQWacYrOdTDGU9yspukA_jQvQoc9I",
  "aiProxy": "https://ai-proxy.goede-aeb.workers.dev",
  "google": false,
  "prompts": [
    {
      "say": "Debate whether cities should ban private cars, three rounds",
      "does": "Sets the motion and round count, then starts the debate."
    },
    {
      "say": "Make the opposition argue like a skeptical economist",
      "does": "Rewrites the opposing persona before the next round."
    },
    {
      "say": "Who is winning so far and why?",
      "does": "Reads the adjudicator's scores and summarizes the clash."
    }
  ]
};
